#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: 2026年 03月 11日 星期三 07:22:42 CST

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/XiaoCRQ/Pictures/Wallpapers/你的名字2k.mp4" &
    sleep 0.1
done
